name: CI JF

on:
  push:
  workflow_dispatch:

permissions:
  actions: write
  attestations: write
  checks: write
  contents: write
  deployments: write
  id-token: write
  issues: write
  discussions: write
  packages: write
  pages: write
  pull-requests: write
  repository-projects: write
  security-events: write
  statuses: write


jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Dependencies
        run: npm install

      - name: Run Tests
        run: npm test

      - name: Create Tarball
        run: npm pack

      # JFrog CLI Setup with OIDC Authentication
      - name: Setup JFrog CLI
        uses: jfrog/setup-jfrog-cli@v4
        env:
          JF_URL: ${{ vars.JF_URL }}
        with:
          oidc-provider-name: setup-jfrog-cli

      # Set Build Name and Number
      - name: Set Build Info
        run: |
          export BUILD_NAME="github-actions-demo-build-main-jf"
          export BUILD_NUMBER=${{ github.run_id }}
          jfrog rt build-collect-env $BUILD_NAME $BUILD_NUMBER

      # Upload Build Artifacts to JFrog
      - name: Upload Build Artifacts to JFrog
        run: |
          jfrog rt upload "*.tgz" "dorr-npm/" --build-name=github-actions-demo-build-main-jf --build-number=${{ github.run_id }}

      # Publish Build Info to JFrog
      - name: Publish Build Info
        run: |
          jfrog rt build-publish github-actions-demo-build-main-jf ${{ github.run_id }}

      # Optional: Scan Build with JFrog Xray
      - name: Scan Build with JFrog Xray
        run: |
          jfrog build-scan github-actions-demo-build-main-jf ${{ github.run_id }}
